// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'zotero-rag-ask-question'
  | 'zotero-rag-chat-header'
  | 'zotero-rag-chat-sidenav'
  | 'zotero-rag-chat-trash-button';
