// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pane-filing-suggestions'
  | 'pane-filing-suggestions-empty'
  | 'pane-filing-suggestions-title'
  | 'pane-item-navigation'
  | 'zotero-rag-ask-question';
