"""
Check whether two embedding presets produce compatible vectors.

Two presets are compatible when vectors generated by one can be queried against
vectors generated by the other — i.e. the same text embedded by both models
lands at cosine similarity ≥ 0.999.  This only holds when both presets use the
exact same underlying model weights without differing pre/post-processing.

Usage:
    uv run python scripts/check_embedding_compat.py
    uv run python scripts/check_embedding_compat.py --preset-a remote-kisski --preset-b apple-silicon-32gb

Models are downloaded automatically on first use via HuggingFace / sentence-transformers.
Remote presets require the corresponding API key to be set in the environment.
"""

import argparse
import asyncio
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent))

from backend.config.presets import PRESETS, get_preset
from backend.services.embeddings import create_embedding_service

# A small, diverse set of probe texts used to compare embeddings.
# Includes short/long, English/German, and technical content to surface any
# preprocessing differences (e.g. instruction prefixes, truncation, normalisation).
PROBE_TEXTS: list[str] = [
    "The mitochondria is the powerhouse of the cell.",
    "Retrieval-augmented generation combines dense retrieval with generative models.",
    "Das Peer-Review-Verfahren dient der wissenschaftlichen Qualitätssicherung.",
    "a",  # edge case: single character
    "transformer attention mechanism self-attention multi-head",  # keyword soup
    (
        "Large language models have demonstrated remarkable few-shot learning capabilities "
        "across a wide range of natural language processing tasks, including question "
        "answering, summarisation, and code generation, often matching or exceeding "
        "specialist fine-tuned models without any task-specific training data."
    ),
    "Zotero ist ein freies Literaturverwaltungsprogramm.",
    "embedding dimensionality cosine similarity dot product normalisation",
    "2024 Nature Reviews Machine Learning transformer architecture survey",
    "How do I cite a preprint in APA format?",
]

COMPAT_THRESHOLD = 0.999  # cosine similarity required to declare compatibility


def cosine(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-12))


def pick_preset(prompt: str) -> str:
    available = sorted(PRESETS.keys())
    print(f"\n{prompt}")
    for i, name in enumerate(available, 1):
        p = PRESETS[name]
        print(f"  {i:2d}. {name:<32s}  [{p.embedding.model_type}] {p.embedding.model_name}")
    while True:
        raw = input("Enter number or preset name: ").strip()
        if raw.isdigit():
            idx = int(raw) - 1
            if 0 <= idx < len(available):
                return available[idx]
        elif raw in PRESETS:
            return raw
        print("  Invalid choice, try again.")


async def embed_all(preset_name: str, texts: list[str]) -> np.ndarray:
    preset = get_preset(preset_name)
    svc = create_embedding_service(preset.embedding)
    print(f"  [{preset_name}] model={preset.embedding.model_name} ({preset.embedding.model_type})")
    print(f"  [{preset_name}] Embedding {len(texts)} probe texts...", flush=True)
    vecs = np.array(await svc.embed_batch(texts))
    if hasattr(svc, "close"):
        svc.close()
    return vecs


async def main() -> None:
    parser = argparse.ArgumentParser(description="Check embedding compatibility between two presets.")
    parser.add_argument("--preset-a", help="First preset")
    parser.add_argument("--preset-b", help="Second preset")
    args = parser.parse_args()

    preset_a = args.preset_a or pick_preset("Select preset A:")
    preset_b = args.preset_b or pick_preset("Select preset B:")

    print(f"\nCompatibility check: {preset_a}  vs  {preset_b}")
    print(f"Probe texts: {len(PROBE_TEXTS)}")
    print(f"Threshold:   cosine >= {COMPAT_THRESHOLD}\n")

    print("Embedding with preset A:")
    vecs_a = await embed_all(preset_a, PROBE_TEXTS)
    print("\nEmbedding with preset B:")
    vecs_b = await embed_all(preset_b, PROBE_TEXTS)

    # Dimension check first — mismatched dims are an instant incompatibility.
    dim_a, dim_b = vecs_a.shape[1], vecs_b.shape[1]
    if dim_a != dim_b:
        print(f"\n[FAIL] Dimension mismatch: {preset_a}={dim_a}  {preset_b}={dim_b}")
        print("       Presets are NOT compatible — vectors cannot share a Qdrant collection.")
        sys.exit(1)

    print(f"\nEmbedding dimension: {dim_a}  (match)\n")

    sims = [cosine(vecs_a[i], vecs_b[i]) for i in range(len(PROBE_TEXTS))]
    min_sim = min(sims)
    mean_sim = sum(sims) / len(sims)
    compatible = all(s >= COMPAT_THRESHOLD for s in sims)

    col = 60
    print(f"{'Probe text':<{col}} {'Cosine':>8}  {'OK?':>4}")
    print("-" * (col + 16))
    for text, sim in zip(PROBE_TEXTS, sims):
        label = "[OK]" if sim >= COMPAT_THRESHOLD else "[FAIL]"
        truncated = text[:col - 3] + "..." if len(text) > col else text
        print(f"{truncated:<{col}} {sim:>8.6f}  {label:>6}")

    print("-" * (col + 16))
    print(f"{'Min cosine:':<{col}} {min_sim:>8.6f}")
    print(f"{'Mean cosine:':<{col}} {mean_sim:>8.6f}")
    print()

    if compatible:
        print(f"[OK] COMPATIBLE — existing vectors from {preset_a} can be queried with {preset_b}.")
        print("     You do NOT need to re-index your library when switching presets.")
    else:
        failures = sum(1 for s in sims if s < COMPAT_THRESHOLD)
        print(f"[FAIL] NOT COMPATIBLE — {failures}/{len(PROBE_TEXTS)} probe texts diverge below threshold.")
        print("       Switching presets requires a full re-index of your library.")
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
